function getchannels() {
    let channeldb = [
        ["index4.html", "NULL"],
        ["index2.html#https://sweet.tv/sk/tv/847-jednotka-hd", "https://pestech28.github.io/back/digivision/v4/ch1.png"],
        ["index2.html#https://sweet.tv/sk/tv/848-dvojka-hd", "https://pestech28.github.io/back/digivision/v4/ch2.png"],
        ["index2.html#https://sweet.tv/sk/tv/849-24-hd", "https://pestech28.github.io/back/digivision/v4/ch3.png"],
        ["index2.html#https://sweet.tv/sk/tv/850-sport-hd", "https://pestech28.github.io/back/digivision/v4/ch4.png"],
        ["index2.html#https://media.joj.sk/embed/3Yz1gBQeKTs?autoplay=1", "https://pestech28.github.io/back/digivision/v4/ch5.png"],
        ["index2.html#https://media.joj.sk/embed/DKZwKhUlV3i?autoplay=1", "https://pestech28.github.io/back/digivision/v4/ch6.png"],
        ["index2.html#https://media.joj.sk/embed/3al7RoqzT3y?autoplay=1", "https://pestech28.github.io/back/digivision/v4/ch7.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch8.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch9.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/family-720.m3u8", "https://pestech28.github.io/back/digivision/v4/ch10.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8", "https://pestech28.github.io/back/digivision/v4/ch11.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch12.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/markiza-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch13.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/doma-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch14.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/dajto-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch15.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/krimi-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch16.png"],
        ["index2.html#https://media.cms.markiza.sk/embed/klasik-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch17.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch18.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch19.png"],
        ["index3.html#https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch20.png"],
        ["index2.html#https://www.ta3.com/live", "https://pestech28.github.io/back/digivision/v4/ch21.png"],
        ["index2.html#https://www.iprima.cz/zive/prima", "https://pestech28.github.io/back/digivision/v4/ch22.png"],
        ["index2.html#https://cnn.iprima.cz/vysilani", "https://pestech28.github.io/back/digivision/v4/ch23.png"],
        ["index2.html#https://garden-tv.mobi/en/channel/DisneyChannel.cz", "https://pestech28.github.io/back/digivision/v4/ch24.png"],
        ["index2.html#https://www.newsnationnow.com/news-nation-live/", "https://pestech28.github.io/back/digivision/v4/ch25.png"],
        ["index2.html#http://v1.weatherscan.net/", "https://pestech28.github.io/back/digivision/v4/ch26.png"],
        ["index3.html#https://retroblast.tv/hls/stream.m3u8", "https://pestech28.github.io/back/digivision/v4/ch27.png"],
        ["index2.html#https://pestech28.github.io/back/digivision/v4/yt/tao.html", "https://pestech28.github.io/back/digivision/v4/ch28.png"],
        ["index.html", "NULL"],
    ];
    return channeldb;
}

function getchinfo() {
    let chinfodb = [
        ["Channel Name", "Channel Description"],
        ["Jednotka", "Všeobecný obsah"],
        ["Dvojka", "Všeobecný a vzdelávací obsah"],
        [":24", "Správy 24 hodín denne, 7 dní v týždni"],
        [":ŠPORT", "Šport 24 hodín denne, 7 dní v týždni"],
        ["TV JOJ", "Televízne programy a filmy"],
        ["JOJ Plus", "Americké televízne relácie"],
        ["JOJ WAU", "Prémiový televízny kanál"],
        ["JOJ SPORT", "Šport 24 hodín denne, 7 dní v týždni"],
        ["JOJ 24", "Správy 24 hodín denne, 7 dní v týždni"],
        ["JOJ Family", "Rodinné relácie a filmy"],
        ["JOJ Cinema", "Filmy"],
        ["JOJKO", "kreslené filmy"],
        ["Marzika", "Rodinný obsah"],
        ["Doma", "Televízne relácie pre ženy"],
        ["Dajto", "Televízne relácie pre mužov"],
        ["Krimi", "Kriminálne seriály"],
        ["Klasik", "Klasické televízne relácie"],
        ["CS History", "Historický kanál"],
        ["CS Film", "Filmový kanál"],
        ["CS Mystery", "Mysteriózne filmy"],
        ["TA3", "Správy 24 hodín denne, 7 dní v týždni"],
        ["Prima SK", "Televízne programy a filmy"],
        ["CNN Prima", "Správy 24 hodín denne, 7 dní v týždni"],
        ["Disney Channel", "kreslené filmy"],
        ["News Nation", "Non bias news 24/7"],
        ["Weather Scan", "Weather info 24/7"],
        ["Cartoon Network", "Cartoons"],
        ["Zen Music", "Traditional Asian music 24/7"],
        ["Channel Name", "Channel Description"],
    ];
    return chinfodb;
}

function getwebchannels() {
    let channeldb = [
        ["https://sweet.tv/sk/tv/847-jednotka-hd", "https://pestech28.github.io/back/digivision/v4/ch1.png"],
        ["https://sweet.tv/sk/tv/848-dvojka-hd", "https://pestech28.github.io/back/digivision/v4/ch2.png"],
        ["https://sweet.tv/sk/tv/849-24-hd", "https://pestech28.github.io/back/digivision/v4/ch3.png"],
        ["https://sweet.tv/sk/tv/850-sport-hd", "https://pestech28.github.io/back/digivision/v4/ch4.png"],
        ["https://media.joj.sk/embed/3Yz1gBQeKTs?autoplay=1", "https://pestech28.github.io/back/digivision/v4/ch5.png"],
        ["https://media.joj.sk/embed/DKZwKhUlV3i?autoplay=1", "https://pestech28.github.io/back/digivision/v4/ch6.png"],
        ["https://media.joj.sk/embed/3al7RoqzT3y?autoplay=1", "https://pestech28.github.io/back/digivision/v4/ch7.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/joj_sport-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch8.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/joj_news-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch9.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/family-720.m3u8", "https://pestech28.github.io/back/digivision/v4/ch10.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cinema-720.m3u8", "https://pestech28.github.io/back/digivision/v4/ch11.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/jojko-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch12.png"],
        ["https://media.cms.markiza.sk/embed/markiza-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch13.png"],
        ["https://media.cms.markiza.sk/embed/doma-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch14.png"],
        ["https://media.cms.markiza.sk/embed/dajto-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch15.png"],
        ["https://media.cms.markiza.sk/embed/krimi-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch16.png"],
        ["https://media.cms.markiza.sk/embed/klasik-live?autoplay=any", "https://pestech28.github.io/back/digivision/v4/ch17.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cs_history-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch18.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cs_film-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch19.png"],
        ["index2.html#https://live.cdn.joj.sk/live/andromeda/cs_mystery-1080.m3u8", "https://pestech28.github.io/back/digivision/v4/ch20.png"],
        ["https://www.ta3.com/live", "https://pestech28.github.io/back/digivision/v4/ch21.png"],
        ["https://www.iprima.cz/zive/prima", "https://pestech28.github.io/back/digivision/v4/ch22.png"],
        ["https://cnn.iprima.cz/vysilani", "https://pestech28.github.io/back/digivision/v4/ch23.png"],
        ["https://garden-tv.mobi/en/channel/DisneyChannel.cz", "https://pestech28.github.io/back/digivision/v4/ch24.png"],
        ["https://www.newsnationnow.com/news-nation-live/", "https://pestech28.github.io/back/digivision/v4/ch25.png"],
        ["http://v1.weatherscan.net/", "https://pestech28.github.io/back/digivision/v4/ch26.png"],
        ["index2.html#https://retroblast.tv/hls/stream.m3u8", "https://pestech28.github.io/back/digivision/v4/ch27.png"],
        ["https://pestech28.github.io/back/digivision/v4/yt/tao.html", "https://pestech28.github.io/back/digivision/v4/ch28.png"],
    ];
    return channeldb;
}
